# Generated by Django 4.1 on 2022-11-12 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('weather', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoodFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepTimeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.ManyToManyField(to='mood.diary')),
                ('factor', models.ManyToManyField(to='mood.factordetail')),
                ('sleep_time', models.ManyToManyField(to='mood.sleeptimefield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='factordetail',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood.moodfactors'),
        ),
        migrations.AddField(
            model_name='diary',
            name='mood',
            field=models.ManyToManyField(related_name='mood', to='mood.factordetail'),
        ),
        migrations.AddField(
            model_name='diary',
            name='people',
            field=models.ManyToManyField(related_name='people', to='mood.factordetail'),
        ),
    ]
