# Generated by Django 4.0.5 on 2022-11-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepTimeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='FactorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood.moodfactors')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('mood', models.ManyToManyField(related_name='mood', to='mood.factordetail')),
                ('people', models.ManyToManyField(related_name='people', to='mood.factordetail')),
            ],
        ),
    ]
