# Generated by Django 4.0.5 on 2022-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='mood',
        ),
        migrations.AddField(
            model_name='diary',
            name='mood',
            field=models.ManyToManyField(related_name='mood', to='mood.factordetail'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='people',
            field=models.ManyToManyField(related_name='people', to='mood.factordetail'),
        ),
        migrations.AlterField(
            model_name='sleeptimefield',
            name='hour',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
